language: elixir
elixir: 1.8
otp_release: 21.0
before_script:
  - curl https://sh.rustup.rs | sh -s -- -y
  - export PATH=$HOME/.cargo/bin:$PATH
jobs:
  include:
    - stage: test
      elixir: 1.5
      otp_release: 19.0
      script: &test_scripts
        - source $HOME/.cargo/env
        - mix test
        - MIX_ENV=test mix credo
        - if [ $CHECK_FORMAT ]; then mix format mix.exs "lib/**/*.{ex,exs}" "test/**/*.{ex,exs}" --check-formatted; fi
    - stage: test
      elixir: 1.6
      otp_release: 20.0
      script: *test_scripts
    - stage: test
      elixir: 1.7
      script: *test_scripts
    - stage: test
      env:
        - CHECK_FORMAT=true
    - stage: test
      env:
        - HTML_PARSER=meeseeks
